# Generated by Django 4.1.1 on 2022-09-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_id',
        ),
    ]
