# Generated by Django 4.1.1 on 2022-09-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0002_remove_card_card_id_remove_topic_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='anki.topic'),
        ),
    ]
